In [1]:
%load_ext autoreload
%autoreload 2

import warnings
from utility.data_processor_helpers import *
from config.paths import RAW_PATH, INTERMEDIATE_PATH
from pandas.tseries.offsets import BMonthEnd

warnings.filterwarnings(action="ignore")

In [3]:
option_path = "spx_options"
start_year = 2015
end_year = 2020

df = load_options(RAW_PATH / option_path, start_year=start_year, end_year=end_year)
df = clean_data(df)
df = reshape_options_long_to_wide(df)

output_file = INTERMEDIATE_PATH / f"full_{option_path}_{start_year}_{end_year}.parquet"
df.to_parquet(output_file, index=True)

Processing year: 2015
  ➤ Extracting spx_eod_2015-amtjlk.7z
Reading tmp/spx_eod_201809.txt
Reading tmp/spx_eod_201808.txt
Reading tmp/spx_eod_201501.txt
Reading tmp/spx_eod_201502.txt
Reading tmp/spx_eod_201503.txt
Reading tmp/spx_eod_201507.txt
Reading tmp/spx_eod_201506.txt
Reading tmp/spx_eod_201512.txt
Reading tmp/spx_eod_201504.txt
Reading tmp/spx_eod_201510.txt
Reading tmp/spx_eod_201511.txt
Reading tmp/spx_eod_201505.txt
Reading tmp/spx_eod_201508.txt
Reading tmp/spx_eod_201509.txt
Reading tmp/spx_eod_201812.txt
Reading tmp/spx_eod_201806.txt
Reading tmp/spx_eod_201807.txt
Reading tmp/spx_eod_201805.txt
Reading tmp/spx_eod_201811.txt
Reading tmp/spx_eod_201810.txt
Reading tmp/spx_eod_201804.txt
Reading tmp/spx_eod_201801.txt
Reading tmp/spx_eod_201803.txt
Reading tmp/spx_eod_201802.txt
Processing year: 2016
  ➤ Extracting spx_eod_2016-rctzlw.7z
Reading tmp/spx_eod_201601.txt
Reading tmp/spx_eod_201603.txt
Reading tmp/spx_eod_201602.txt
Reading tmp/spx_eod_201606.txt
Reading tmp/spx_eod_201612.txt
Reading tmp/spx_eod_201607.txt
Reading tmp/spx_eod_201611.txt
Reading tmp/spx_eod_201605.txt
Reading tmp/spx_eod_201604.txt
Reading tmp/spx_eod_201610.txt
Reading tmp/spx_eod_201609.txt
Reading tmp/spx_eod_201608.txt
Processing year: 2017
  ➤ Extracting spx_eod_2017-xspity.7z
Reading tmp/spx_eod_201703.txt
Reading tmp/spx_eod_201702.txt
Reading tmp/spx_eod_201701.txt
Reading tmp/spx_eod_201711.txt
Reading tmp/spx_eod_201705.txt
Reading tmp/spx_eod_201704.txt
Reading tmp/spx_eod_201710.txt
Reading tmp/spx_eod_201706.txt
Reading tmp/spx_eod_201712.txt
Reading tmp/spx_eod_201707.txt
Reading tmp/spx_eod_201709.txt
Reading tmp/spx_eod_201708.txt
Processing year: 2018
  ➤ Extracting spx_eod_2018-uqawfl.7z
Reading tmp/spx_eod_201809.txt
Reading tmp/spx_eod_201808.txt
Reading tmp/spx_eod_201812.txt
Reading tmp/spx_eod_201806.txt
Reading tmp/spx_eod_201807.txt
Reading tmp/spx_eod_201805.txt
Reading tmp/spx_eod_201811.txt
Reading tmp/spx_eod_201810.txt
Reading tmp/spx_eod_201804.txt
Reading tmp/spx_eod_201801.txt
Reading tmp/spx_eod_201803.txt
Reading tmp/spx_eod_201802.txt
Processing year: 2019
  ➤ Extracting spx_eod_2019-chxexe.7z
Reading tmp/spx_eod_201909.txt
Reading tmp/spx_eod_201908.txt
Reading tmp/spx_eod_201905.txt
Reading tmp/spx_eod_201911.txt
Reading tmp/spx_eod_201910.txt
Reading tmp/spx_eod_201904.txt
Reading tmp/spx_eod_201912.txt
Reading tmp/spx_eod_201906.txt
Reading tmp/spx_eod_201907.txt
Reading tmp/spx_eod_201903.txt
Reading tmp/spx_eod_201902.txt
Reading tmp/spx_eod_201901.txt
Processing year: 2020
  ➤ Extracting spx_eod_2020-wh6jt7.7z
Reading tmp/spx_eod_202008.txt
Reading tmp/spx_eod_202009.txt
Reading tmp/spx_eod_202001.txt
Reading tmp/spx_eod_202002.txt
Reading tmp/spx_eod_202003.txt
Reading tmp/spx_eod_202007.txt
Reading tmp/spx_eod_202012.txt
Reading tmp/spx_eod_202006.txt
Reading tmp/spx_eod_202010.txt
Reading tmp/spx_eod_202004.txt
Reading tmp/spx_eod_202005.txt
Reading tmp/spx_eod_202011.txt

ValueError: Index contains duplicate entries, cannot reshape

In [ ]:
a = reshape_options_long_to_wide(df.loc["2018"])

In [16]:
df.loc["2018"]

,underlying_last,expiry,dte,strike,strike_distance,strike_distance_pct,delta,gamma,vega,theta,rho,iv,volume,last,bid,ask,option_type,size_bid,size_ask
date,,,,,,,,,,,,,,,,,,,
2018-01-02,2695.87,2018-01-19,17.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2589.51,2595.99,C,4,5
2018-01-02,2695.87,2018-06-15,164.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2569.21,2577.20,C,11,10
2018-01-02,2695.87,2018-12-21,353.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2540.20,2557.21,C,1,1
2018-01-02,2695.87,2019-12-20,717.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,1.0,2481.60,2493.50,2510.10,C,2,1
2018-01-02,2695.87,2020-12-18,1081.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2457.90,2466.80,C,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31,2506.71,2019-09-20,263.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89978,0.0,0.0,NaN,0.0,0.00,1651.60,1661.90,P,100,100
2018-12-31,2506.71,2019-09-30,273.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89992,0.0,0.0,NaN,0.0,0.00,1655.40,1674.20,P,1,1
2018-12-31,2506.71,2019-12-20,354.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89959,0.0,0.0,NaN,23.0,1632.00,1634.90,1650.40,P,100,100
2018-12-31,2506.71,2020-06-19,536.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89972,0.0,0.0,NaN,0.0,0.00,1604.31,1625.00,P,100,15
2018-12-31,2506.71,2020-12-18,718.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89963,0.0,0.0,NaN,2.0,1423.66,1583.30,1598.90,P,150,5

In [31]:
a = df.loc["2018"]

In [27]:
a.index.duplicated().sum()

0

In [28]:
a

,date,underlying_last,expiry,dte,strike,strike_distance,strike_distance_pct,delta,gamma,vega,theta,rho,iv,volume,last,bid,ask,option_type,size_bid,size_ask
0,2018-01-02,2695.87,2018-01-19,17.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2589.51,2595.99,C,4,5
1,2018-01-02,2695.87,2018-06-15,164.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2569.21,2577.20,C,11,10
2,2018-01-02,2695.87,2018-12-21,353.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2540.20,2557.21,C,1,1
3,2018-01-02,2695.87,2019-12-20,717.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,1.0,2481.60,2493.50,2510.10,C,2,1
4,2018-01-02,2695.87,2020-12-18,1081.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2457.90,2466.80,C,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5529339,2018-12-31,2506.71,2019-09-20,263.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89978,0.0,0.0,NaN,0.0,0.00,1651.60,1661.90,P,100,100
5529340,2018-12-31,2506.71,2019-09-30,273.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89992,0.0,0.0,NaN,0.0,0.00,1655.40,1674.20,P,1,1
5529341,2018-12-31,2506.71,2019-12-20,354.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89959,0.0,0.0,NaN,23.0,1632.00,1634.90,1650.40,P,100,100
5529342,2018-12-31,2506.71,2020-06-19,536.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89972,0.0,0.0,NaN,0.0,0.00,1604.31,1625.00,P,100,15
5529343,2018-12-31,2506.71,2020-12-18,718.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89963,0.0,0.0,NaN,2.0,1423.66,1583.30,1598.90,P,150,5

In [33]:
a

,date,underlying_last,expiry,dte,strike,strike_distance,strike_distance_pct,delta,gamma,vega,theta,rho,iv,volume,last,bid,ask,option_type,size_bid,size_ask
0,2018-01-02,2695.87,2018-01-19,17.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2589.51,2595.99,C,4,5
1,2018-01-02,2695.87,2018-06-15,164.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2569.21,2577.20,C,11,10
2,2018-01-02,2695.87,2018-12-21,353.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2540.20,2557.21,C,1,1
3,2018-01-02,2695.87,2019-12-20,717.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,1.0,2481.60,2493.50,2510.10,C,2,1
4,2018-01-02,2695.87,2020-12-18,1081.0,100.0,2595.9,0.963,1.0,0.0,0.00000,0.0,0.0,NaN,0.0,0.00,2457.90,2466.80,C,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5529339,2018-12-31,2506.71,2019-09-20,263.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89978,0.0,0.0,NaN,0.0,0.00,1651.60,1661.90,P,100,100
5529340,2018-12-31,2506.71,2019-09-30,273.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89992,0.0,0.0,NaN,0.0,0.00,1655.40,1674.20,P,1,1
5529341,2018-12-31,2506.71,2019-12-20,354.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89959,0.0,0.0,NaN,23.0,1632.00,1634.90,1650.40,P,100,100
5529342,2018-12-31,2506.71,2020-06-19,536.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89972,0.0,0.0,NaN,0.0,0.00,1604.31,1625.00,P,100,15
5529343,2018-12-31,2506.71,2020-12-18,718.0,4200.0,1693.3,0.675,-1.0,0.0,-16942.89963,0.0,0.0,NaN,2.0,1423.66,1583.30,1598.90,P,150,5

In [32]:
if a.index.name == "date":
    a = a.reset_index()

cols_to_include = [
    'date',
    'underlying_last',
    'expiry',
    'dte',
    'strike',
    'strike_distance',
    'strike_distance_pct'
]

non_option_cols = [col for col in df.columns if col in cols_to_include]
wide_df = a.pivot(index=non_option_cols, columns="option_type")
wide_df.columns = [f"{opt.lower()}_{col.lower()}" for col, opt in wide_df.columns]

ValueError: Index contains duplicate entries, cannot reshape